package ru.prusov.TelegramBotConstructionHelper.usecase.state;

public enum UserState {
    NONE,
    LOAD_LOGO,
    WAITING_CONSTRUCTION_ITEM_TITLE,
    WAITING_CONSTRUCTION_ITEM_PHOTO,
    WAITING_CONSTRUCTION_ITEM_DESCRIPTION,
    WAITING_CONSTRUCTION_ARTICLE_NUMBER,
    WAITING_AUTOMATION_ARTICLE_NUMBER,
    WAITING_ARTICLE_TITLE,
    WAITING_ARTICLE_DESCRIPTION,
    CONTRACT_END,
    CONTRACT_START,
    CONTRACT_NUMBER,
    CONTRACT_REMOVE,
    CONTRACT_UPDATE,
    CONTRACT_AMOUNT,
    CONTRACT_CUSTOMER,
    CONTRACT_CONTRACTOR,
    CONTRACT_DESCRIPTION,
    WAITING_UPDATE_CONTRACT,
    WAITING_UPDATE_CONTRACT_END,
    WAITING_UPDATE_CONTRACT_START,
    WAITING_UPDATE_CONTRACT_AMOUNT,
    WAITING_UPDATE_OPTIONS_CONTRACT,
    WAITING_UPDATE_CONTRACT_DESCRIPTION,

    WAITING_PAYMENT_CONTRACT_NUMBER;


}
