package ru.prusov.TelegramBotConstructionHelper.usecase.state;

public enum UserState {
    NONE,
    LOAD_LOGO,
    WAITING_CONSTRUCTION_ITEM_TITLE,
    WAITING_CONSTRUCTION_ITEM_PHOTO,
    WAITING_CONSTRUCTION_ITEM_DESCRIPTION,
    WAITING_CONSTRUCTION_ARTICLE_NUMBER;
}
