version: '3.9'
services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_tbcha
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - mynet

volumes:
  grafana-data:

networks:
  mynet:
    external: true
