spring:
  application:
    name: TelegramBotConstructionHelper
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-ddl: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

bot:
  botUsername: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}

server:
  port: 8080


admin:
  chatId: 5151658826

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true