spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/construction_db
    username: arty
    password: arty
    driver-class-name: org.postgresql.Driver

bot:
  botUsername: Norman
  botToken: 7278897959:AAGbd9Hb69O8TNPs9zKt5LfSS7EDOG4ek8U