spring:
  application:
    name: TelegramBotConstructionHelper

  datasource:
    url: jdbc:postgresql://localhost:5445/construction_db
    username: arty
    password: arty
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-ddl: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

bot:
  botUsername: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}
server:
  port: 8081

admin:
  chatId: 5151658826