spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

bot:
  botUsername: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}

